export const NavItems = [
  { name: "Home", href: "/" },
  { name: "About", href: "/about" },
  { name: "Blog", href: "/blogs" },
];

export const authMenuItems = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Write a new post", href: "/dashboard/newpost" },
  { name: "My Blog posts", href: "/dashboard/blogposts" },
  { name: "Profile", href: "/dashboard/profile" },
];

export const POSTS = [
  {
    id: 1,
    img: `/blogs/blog2.svg`,
    tag: "Enterprise",
    title: "The key new features and changes in Tailwind CSS",
    desc: "Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens bed design but the back is too high for the beams and angle of the ceiling I also wanted to point out.",
    date: "10 September 2022",
    author: {
      img: `/authors/avatar1.jpg`,
      name: "Ryan Samuel",
    },
  },
  {
    id: 2,
    img: `/blogs/blog6.svg`,
    tag: "Startups",
    title: "Lyft launching cross-platform service this week",
    desc: "Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens bed design but the back is too high for the beams and angle of the ceiling I also wanted to point out.",
    date: "12 September 2022",
    author: {
      img: `/authors/avatar2.jpg`,
      name: "Nora Hazel",
    },
  },
  {
    id: 3,
    img: `/blogs/blog3.svg`,
    tag: "Trending",
    title: "6 insights into the French Fashion landscape",
    desc: "Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens bed design but the back is too high for the beams and angle of the ceiling I also wanted to point out.",
    date: "16 September 2022",
    author: {
      img: `/authors/avatar2.jpg`,
      name: "Otto Gonzalez",
    },
  },
  {
    id: 4,
    img: `/blogs/blog4.svg`,
    tag: "Lifestyle",
    title: "Autodesk looks to future of 3D printing with Project",
    desc: "Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens bed design but the back is too high for the beams and angle of the ceiling I also wanted to point out.",
    date: "18 September 2022",
    author: {
      img: `/authors/avatar3.jpg`,
      name: "Ryan Samuel",
    },
  },
  {
    id: 5,
    img: `/blogs/blog5.svg`,
    tag: "Enterprise",
    title: "Autodesk looks to future of 3D printing with Project",
    desc: "Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens bed design but the back is too high for the beams and angle of the ceiling I also wanted to point out.",
    date: "10 September 2022",
    author: {
      img: `/authors/avatar3.jpg`,
      name: "Ryan Samuel",
    },
  },
  {
    id: 6,
    img: `/blogs/blog6.svg`,
    tag: "Startups",
    title: "Lyft launching cross-platform service this week",
    desc: "Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens bed design but the back is too high for the beams and angle of the ceiling I also wanted to point out.",
    date: "12 September 2022",
    author: {
      img: `/authors/avatar2.jpg`,
      name: "Nora Hazel",
    },
  },
];
export const TECH_POSTS = [
  {
    id: 1,
    img: `/blogs/blog-1.svg`,
    tag: "Tech",
    title: "The Evolution of JavaScript Frameworks",
    desc: "Explore how JavaScript frameworks have changed the way we build web applications, from jQuery to React and beyond.",
    date: "03 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 2,
    img: `/blogs/blog-2.png`,
    tag: "Tech",
    title: "Why TypeScript is Taking Over",
    desc: "TypeScript brings type safety to JavaScript. Discover why more developers are adopting it for large-scale projects.",
    date: "05 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 3,
    img: `/blogs/blog-3.png`,
    tag: "Tech",
    title: "Next.js: The Future of SSR",
    desc: "Server-side rendering is back in fashion. Learn how Next.js makes SSR easy and efficient for modern apps.",
    date: "07 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 4,
    img: `/blogs/blog-13.png`,
    tag: "Tech",
    title: "Understanding React Hooks",
    desc: "Hooks revolutionized React development. Get practical tips for using useState, useEffect, and custom hooks.",
    date: "09 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 5,
    img: `/blogs/blog5.svg`,
    tag: "Tech",
    title: "Building APIs with NestJS",
    desc: "NestJS offers a powerful way to build scalable APIs. See how decorators and modules simplify backend code.",
    date: "11 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 6,
    img: `/blogs/blog6.svg`,
    tag: "Tech",
    title: "Deploying Apps with Vercel",
    desc: "Vercel makes deployment seamless for frontend projects. Learn how to set up CI/CD and preview deployments.",
    date: "13 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
];

export const DESIGN_POSTS = [
  {
    id: 1,
    img: `/blogs/blog-2.png`,
    tag: "Design",
    title: "Minimalism in UI Design",
    desc: "Minimalist design is trending. Discover how to create clean, user-friendly interfaces.",
    date: "04 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 2,
    img: `/blogs/blog-3.png`,
    tag: "Design",
    title: "Color Theory for Developers",
    desc: "Learn the basics of color theory and how to apply it to your web projects.",
    date: "06 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 3,
    img: `/blogs/blog4.svg`,
    tag: "Design",
    title: "Typography Matters",
    desc: "Good typography improves readability and user experience. See how to choose the right fonts.",
    date: "08 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 4,
    img: `/blogs/blog5.svg`,
    tag: "Design",
    title: "Dark Mode: Best Practices",
    desc: "Dark mode is popular, but it needs careful design. Tips for accessibility and aesthetics.",
    date: "10 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 5,
    img: `/blogs/blog6.svg`,
    tag: "Design",
    title: "Responsive Layouts with CSS Grid",
    desc: "CSS Grid makes responsive design easier. Learn layout techniques for all devices.",
    date: "12 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 6,
    img: `/blogs/blog-1.svg`,
    tag: "Design",
    title: "Animations that Delight Users",
    desc: "Subtle animations can enhance UX. See examples and code for smooth transitions.",
    date: "14 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
];

export const BUSINESS_POSTS = [
  {
    id: 1,
    img: `/blogs/blog-3.png`,
    tag: "Business",
    title: "How Startups Scale Fast",
    desc: "Scaling a startup is challenging. Learn strategies from successful founders.",
    date: "05 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 2,
    img: `/blogs/blog-2.png`,
    tag: "Business",
    title: "Remote Teams: Pros and Cons",
    desc: "Remote work is here to stay. Explore the benefits and challenges for businesses.",
    date: "07 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 3,
    img: `/blogs/blog5.svg`,
    tag: "Business",
    title: "Funding Your Startup",
    desc: "From bootstrapping to venture capital, find the best funding options for your business.",
    date: "09 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 4,
    img: `/blogs/blog6.svg`,
    tag: "Business",
    title: "Brand Building in 2022",
    desc: "Branding is more than a logo. Learn how to build a memorable brand identity.",
    date: "11 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 5,
    img: `/blogs/blog-1.svg`,
    tag: "Business",
    title: "Networking for Entrepreneurs",
    desc: "Networking opens doors. Tips for building valuable connections in your industry.",
    date: "13 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 6,
    img: `/blogs/blog-2.png`,
    tag: "Business",
    title: "The Power of Customer Feedback",
    desc: "Customer feedback drives growth. Learn how to collect and use it effectively.",
    date: "15 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
];

export const LIFESTYLE_POSTS = [
  {
    id: 1,
    img: `/blogs/blog-10.jpeg`,
    tag: "Lifestyle",
    title: "Work-Life Balance for Developers",
    desc: "Coding can be intense. Discover ways to maintain balance and avoid burnout.",
    date: "06 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 2,
    img: `/blogs/blog-12.jpeg`,
    tag: "Lifestyle",
    title: "Healthy Habits for Remote Workers",
    desc: "Remote work offers flexibility. Learn habits to stay healthy and productive.",
    date: "08 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 3,
    img: `/blogs/blog6.svg`,
    tag: "Lifestyle",
    title: "Traveling While Working Remotely",
    desc: "Digital nomads share tips for working while exploring new places.",
    date: "10 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 4,
    img: `/blogs/blog-1.svg`,
    tag: "Lifestyle",
    title: "Mindfulness for Developers",
    desc: "Mindfulness can improve focus and reduce stress. Simple practices for busy coders.",
    date: "12 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 5,
    img: `/blogs/blog-2.png`,
    tag: "Lifestyle",
    title: "Home Office Setup Ideas",
    desc: "Create a workspace that boosts productivity and comfort.",
    date: "14 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 6,
    img: `/blogs/blog-3.png`,
    tag: "Lifestyle",
    title: "Balancing Fitness and Coding",
    desc: "Stay active while working long hours at the computer.",
    date: "16 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
];

export const TRENDING_POSTS = [
  {
    id: 1,
    img: `/blogs/blog5.svg`,
    tag: "Trending",
    title: "The Rise of No-Code Platforms",
    desc: "No-code tools are empowering non-developers. See how they're changing the tech landscape.",
    date: "07 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 2,
    img: `/blogs/blog6.svg`,
    tag: "Trending",
    title: "Web3: The Next Internet Revolution",
    desc: "Web3 promises decentralization and new opportunities. What does it mean for developers?",
    date: "09 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 3,
    img: `/blogs/blog-12.jpeg`,
    tag: "Trending",
    title: "Sustainable Tech: Green Coding",
    desc: "Eco-friendly coding practices are gaining traction. Learn how to reduce your carbon footprint.",
    date: "11 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
  {
    id: 4,
    img: `/blogs/blog-13.png`,
    tag: "Trending",
    title: "The Future of Remote Collaboration",
    desc: "Remote teams need new tools. Explore the latest in virtual collaboration.",
    date: "13 October 2022",
    author: { img: `/authors/avatar2.jpg`, name: "Nora Hazel" },
  },
  {
    id: 5,
    img: `/blogs/blog-3.png`,
    tag: "Trending",
    title: "AI in Everyday Life",
    desc: "Artificial intelligence is everywhere. See how it's impacting daily routines.",
    date: "15 October 2022",
    author: { img: `/authors/avatar3.jpg`, name: "Otto Gonzalez" },
  },
  {
    id: 6,
    img: `/blogs/blog-10.jpeg`,
    tag: "Trending",
    title: "The Growth of Mobile-First Design",
    desc: "Mobile-first is now the standard. Tips for designing for small screens.",
    date: "17 October 2022",
    author: { img: `/authors/avatar1.jpg`, name: "Ryan Samuel" },
  },
];
